# Generated by Django 3.2.9 on 2022-01-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crseed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processparam',
            name='jackett_prowlarr',
            field=models.IntegerField(choices=[(0, 'Jackett'), (1, 'Prowlarr')], default=0),
        ),
        migrations.AddField(
            model_name='processparam',
            name='skip_CJK',
            field=models.BooleanField(default=True),
        ),
    ]
