# Generated by Django 3.2.8 on 2022-02-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crseed', '0002_auto_20220124_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='processparam',
            name='category_indexers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processparam',
            name='indexer_audio',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processparam',
            name='indexer_ebook',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processparam',
            name='indexer_movietv',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processparam',
            name='indexer_music',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processparam',
            name='indexer_other',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
