# Generated by Django 3.2.8 on 2022-02-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crseed', '0003_auto_20220207_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='processparam',
            name='skip_check',
            field=models.BooleanField(default=False),
        ),
    ]
