# Generated by Django 3.2.12 on 2022-05-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crseed', '0004_auto_20220419_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='crosstorrent',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
    ]
