# Generated by Django 3.2.12 on 2022-05-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crseed', '0005_crosstorrent_fixed'),
    ]

    operations = [
        migrations.AddField(
            model_name='processparam',
            name='fix_docker_dir',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='processparam',
            name='fix_real_dir',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='processparam',
            name='map_dir',
            field=models.BooleanField(default=False),
        ),
    ]
