# Generated by Django 3.2.12 on 2022-05-05 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crseed', '0006_auto_20220503_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processparam',
            old_name='fix_docker_dir',
            new_name='map_from_path',
        ),
        migrations.RenameField(
            model_name='processparam',
            old_name='fix_real_dir',
            new_name='map_to_path',
        ),
    ]
